# Codedark â€” Visual Studio Code dark default inspired
# by tomasiser

bg = "#1E1E1E"
bg_light = "#252526"
fg = "#D4D4D4"
fg_dim = "#6A6A6A"

red = "#F44747"
green = "#608B4E"
yellow = "#DCDCAA"
blue = "#569CD6"
magenta = "#C586C0"
cyan = "#4EC9B0"
orange = "#CE9178"

border_active = "blue"
border_inactive = "#3C3C3C"
status_bg = "#161616"
cursor_line = "#282828"

dir_color = "blue"
symlink_color = "cyan"
file_color = "fg"
