# Dark Fox â€” deep dark variant of Nightfox family
# by EdenEast

bg = "#000000"
bg_light = "#131A24"
fg = "#CDCECF"
fg_dim = "#71839B"

red = "#C94F6D"
green = "#81B29A"
yellow = "#DBC074"
blue = "#719CD6"
magenta = "#9D79D6"
cyan = "#63CDCF"
orange = "#F4A261"

border_active = "blue"
border_inactive = "#1D2A39"
status_bg = "#000000"
cursor_line = "#131A24"

dir_color = "blue"
symlink_color = "cyan"
file_color = "fg"
