# Embark â€” ambitious dark theme
# by Noel Cower

bg = "#1E1C31"
bg_light = "#2D2B40"
fg = "#CBE3E7"
fg_dim = "#585273"

red = "#F02E6E"
green = "#62D196"
yellow = "#FFE6B3"
blue = "#91DDFF"
magenta = "#D4BFFF"
cyan = "#87DFEB"
orange = "#F2B482"

border_active = "magenta"
border_inactive = "#3E3859"
status_bg = "#100E23"
cursor_line = "#2D2B40"

dir_color = "blue"
symlink_color = "cyan"
file_color = "fg"
